# Generated by Django 5.1.1 on 2024-11-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_place_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ad Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bathrooms')),
                ('furnishing', models.CharField(choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi-Furnished'), ('unfurnished', 'Un-Furnished')], max_length=50, verbose_name='Furnishing')),
                ('construction_status', models.CharField(choices=[('new_launch', 'New Launch'), ('ready_to_move', 'Ready to Move'), ('under_construction', 'Under Construction')], max_length=50, verbose_name='Construction Status')),
                ('super_built_up_area', models.FloatField(blank=True, null=True, verbose_name='Super Built-up Area (ft)')),
                ('carpet_area', models.FloatField(blank=True, null=True, verbose_name='Carpet Area (ft)')),
                ('maintenance', models.FloatField(blank=True, null=True, verbose_name='Maintenance (Monthly)')),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Floors')),
                ('floor_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='Floor No')),
                ('facing', models.CharField(blank=True, max_length=50, null=True, verbose_name='Facing')),
                ('projects_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Projects')),
                ('price', models.FloatField(verbose_name='Price')),
                ('ecxact_location', models.CharField(max_length=255, verbose_name='Location')),
                ('listed_by', models.CharField(choices=[('builder', 'Builder'), ('dealer', 'Dealer'), ('owner', 'Owner')], max_length=50, verbose_name='Listed by')),
                ('listed_by_photo', models.ImageField(blank=True, null=True, upload_to='property_photos/', verbose_name='Upload Photos')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('mainphoto', models.ImageField(blank=True, null=True, upload_to='property_photos/', verbose_name='Upload Photos')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='property_photos/', verbose_name='Upload Photos')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='property_photos/', verbose_name='Upload Photos')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='property_photos/', verbose_name='Upload Photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.mainplace')),
            ],
        ),
    ]
