# Generated by Django 5.1.1 on 2024-11-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='buy_or_rent',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], default='buy', max_length=10, verbose_name='Buy or Rent'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='is_favarite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='listed_by_name',
            field=models.CharField(default=1, max_length=255, verbose_name='lname'),
            preserve_default=False,
        ),
    ]
